spring:
  profiles:
    active:
    - dev
---
server: 
    port: 7001   #注册中心占用7001端口，冒号后面必须要有空格

spring: 
    profiles: dev
    application: 
        name: microservice-config-eureka-client
        
eureka: 
    instance: 
        hostname: wxjown.eureka.com 
    client: 
        register-with-eureka: false  #表示当前的eureka-server自己不注册进服务列表中
        fetch-registry: false     #表示不通过eureka获取注册信息
        service-url: 
            defaultZone: http://wxjown.eureka7001.com:7001/eureka/
---
server: 
    port: 7001   #注册中心占用7001端口，冒号后面必须要有空格

spring: 
    profiles: test
    application: 
        name: microservice-config-eureka-client
        
eureka: 
    instance: 
        hostname: wxjown.eureka.com 
    client: 
        register-with-eureka: false  #表示当前的eureka-server自己不注册进服务列表中
        fetch-registry: false     #表示不通过eureka获取注册信息
        service-url: 
            defaultZone: http://wxjown.eureka7001.com:7001/eureka/
    
##该上传文件必须是UTF-8格式的文件